# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build corne nice_nano_v2'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      alphas: '["qwerty"]'
      nav: '["vi"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y\\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=5400000"]'

