# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build minidox nice_nano_v2'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      board: '["nice_nano_v2"]'
      shield: '["minidox_left","minidox_right"]'
      alphas: '["colemak"]'
      nav: '["invertedt"]'
      layers: '["flip"]'
      clipboard: '["win"]'
